SELECT * FROM BOOKS

INSERT INTO BOOKS VALUES(2, 'MOWGLI', 'CLEARSTONE', 4)
INSERT INTO BOOKS VALUES(3, 'THE REPUBLIC', 'PLATO', 4)

UPDATE BOOKS
SET COUNT=7
WHERE ID=3

DELETE FROM BOOKS
WHERE ID=2

SELECT * FROM BOOK_ISSUE
SELECT * FROM LIBRARY_VISITOR_USER

